# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [5]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/shahz/anaconda3/Library/include
    lib directory: C:/Users/shahz/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3. Create a null vector of size 10

In [9]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [46]:

import numpy as np

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


800 bytes


#### 5. How to get the documentation of the numpy add function from the command line?

In [13]:
import numpy as np

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [17]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [26]:
import numpy as np

v = np.arange(15, 49)

print(v)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last)

In [28]:
import numpy as np
arr = np.array([2, 5, 8, 14, 25])
print(arr[::-1])

[25 14  8  5  2]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
import numpy as np
print(np.arange(2, 11).reshape(3, 3))


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [32]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [34]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [36]:
import numpy as np

random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.13082876 0.85459718 0.23684149]
  [0.62570677 0.93923702 0.57913449]
  [0.82761189 0.47080564 0.86754623]]

 [[0.92623465 0.49485775 0.26872422]
  [0.65030811 0.04975724 0.03283801]
  [0.11519802 0.7915753  0.79961515]]

 [[0.03514747 0.9107927  0.91692015]
  [0.21069182 0.10509977 0.85738848]
  [0.42905302 0.62692713 0.04565635]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


0.003002219014836327 0.9969706595429274


#### 14. Create a random vector of size 30 and find the mean value

In [42]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(m)


0.5519836414564107


#### 15. Create a 2d array with 1 on the border and 0 inside

In [52]:
import numpy as np
rows = 5
cols = 5

array = np.zeros((rows, cols))

array[0, :] = 1  
array[-1, :] = 1  
array[:, 0] = 1  
array[:, -1] = 1 

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [58]:
import numpy as np
rows = 5
cols = 5

array = np.zeros((rows, cols))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [60]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [62]:
import numpy as np

Z = np.diag([1, 2, 3, 4], k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [64]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [68]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [70]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [72]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.60854804 -0.14200213  1.5283713  -1.21644048 -0.26531252]
 [ 1.4629652  -1.50685664  0.87917047 -0.8958756  -0.88798003]
 [ 1.52770079 -0.55551853 -0.27853437  1.25128864  0.71429584]
 [-0.37197107 -0.41201649  0.63188973 -1.47354889 -1.23059517]
 [-0.28573015  1.44926068 -0.68584426  1.10086178 -0.94612618]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [76]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [78]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [82]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [84]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [88]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\shahz\AppData\Local\Temp\ipykernel_11912\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\shahz\AppData\Local\Temp\ipykernel_11912\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\shahz\AppData\Local\Temp\ipykernel_11912\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ?

In [92]:
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-7.  6. -3.  2.  1. 10.  3.  3.  3.  5.]


#### 30. How to find common values between two arrays?

In [94]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 4 9]


#### 31. How to ignore all numpy warnings (not recommended)?

In [104]:

np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [106]:
 np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [110]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [114]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,"\n",today,"\n",tomorrow)

2024-07-04 
 2024-07-05 
 2024-07-06


#### 34. How to get all the dates corresponding to the month of July 2016?

In [116]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [118]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [120]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[3. 1. 2. 0. 1. 4. 1. 3. 5. 7.]
[3. 1. 2. 0. 1. 4. 1. 3. 5. 7.]
[3. 1. 2. 0. 1. 4. 1. 3. 5. 7.]
[3 1 2 0 1 4 1 3 5 7]
[3. 1. 2. 0. 1. 4. 1. 3. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [122]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [124]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [126]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [128]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06661572 0.13870827 0.22190736 0.2309736  0.31788281 0.31852565
 0.49104706 0.50499315 0.60338007 0.93471698]


#### 41. How to sum a small array faster than np.sum?

In [130]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal

In [132]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) 

In [134]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [136]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.26845407 0.32584663 0.57978073 0.94269233 0.89223856 0.36220771
 0.91023929 0.92726692 0.69490936 0.6368897 ]
[0.7396707  0.96522015 0.74646688 1.17019671 0.03908798 0.27235605
 0.86525165 0.47498419 1.19019987 0.18033772]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [138]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.22531706 0.80566198 0.65849898 0.59024851 0.21006124 0.22214095
 0.72883269 0.         0.47671784 0.73718209]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [140]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [142]:

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [144]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? 

In [146]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector?

In [148]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

12


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [150]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\shahz\AppData\Local\Temp\ipykernel_11912\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [152]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.5997929  0.39453057 0.45431998 0.45820398 0.08880048
  0.5479646  0.14505647 0.11012421 0.44130206]
 [0.5997929  0.         0.62235617 1.00280957 0.73158085 0.5259257
  1.13560505 0.50360236 0.70176746 0.15864458]
 [0.39453057 0.62235617 0.         0.48599353 0.8407373  0.42703403
  0.66957379 0.47881234 0.47264452 0.50162356]
 [0.45431998 1.00280957 0.48599353 0.         0.82654022 0.54284034
  0.19357972 0.59860631 0.41112898 0.84926343]
 [0.45820398 0.73158085 0.8407373  0.82654022 0.         0.41388664
  0.82732964 0.36653415 0.43214574 0.62032316]
 [0.08880048 0.5259257  0.42703403 0.54284034 0.41388664 0.
  0.6343018  0.06087273 0.17642963 0.36906467]
 [0.5479646  1.13560505 0.66957379 0.19357972 0.82732964 0.6343018
  0.         0.68101525 0.47013526 0.97790735]
 [0.14505647 0.50360236 0.47881234 0.59860631 0.36653415 0.06087273
  0.68101525 0.         0.21350752 0.35129983]
 [0.11012421 0.70176746 0.47264452 0.41112898 0.43214574 0.17642963
  0.47013526 0.2135075

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [156]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[19  8 61 40 81 15 29 85 96 91]


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays?

In [161]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array

In [163]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array?

In [165]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix

In [167]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.34295955  0.2478182  -0.32231659  0.00908417  0.21066158 -0.10325086
   0.30490426 -0.38116626 -0.22142346 -0.08727059]
 [ 0.18441372 -0.38219283  0.37875177 -0.07189649 -0.10090018  0.30197913
   0.34145811 -0.21475754 -0.10660633 -0.33024936]
 [ 0.11009124 -0.3876609   0.00289998  0.01955264  0.26467672  0.06496475
  -0.3186523   0.12286362  0.06288927  0.05837498]
 [-0.3891149   0.30454266  0.04949582  0.29944831 -0.49545742  0.01583393
   0.04472274  0.32849694 -0.00399974 -0.15396834]
 [ 0.44320749 -0.26217432 -0.43714301 -0.51969077  0.22953379  0.08764565
   0.31188155  0.29722903 -0.34226835  0.19177893]]


#### 59. How to sort an array by the nth column?

In [169]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 4 4]
 [6 1 3]
 [9 6 0]]
[[6 1 3]
 [9 4 4]
 [9 6 0]]


#### 60. How to tell if a given 2D array has null columns?

In [171]:
# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array

In [174]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6018907226243936


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [176]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [178]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [180]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 2. 4. 3. 2. 5. 3. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [182]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [184]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [186]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 53 64 55]
 [43 51 65 58]
 [40 59 74 45]]
[[53 53 64 55]
 [43 51 65 58]
 [40 59 74 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [188]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.45022977 0.48218205 0.61156365 0.59713167 0.40890011 0.45305986
 0.42448281 0.45383075 0.50688178 0.47769098]


#### 69. How to get the diagonal of a dot product?

In [192]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)


array([1.09344564, 1.93342423, 2.630352  , 1.99819417, 0.86664425])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [194]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [196]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array?

In [198]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [199]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 21) ( 2, 81) ( 5, 12) ( 5, 74) ( 6, 36) ( 6, 39) ( 7, 18) ( 7, 86)
 (12, 35) (12, 72) (12, 74) (18, 86) (21, 81) (28, 59) (28, 78) (30, 68)
 (30, 83) (32, 41) (32, 50) (35, 72) (36, 39) (41, 50) (58, 60) (58, 84)
 (59, 78) (60, 84) (68, 83) (76, 79) (76, 90) (79, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [202]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array?

In [203]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [208]:
import numpy as np
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [210]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.96814537, -0.84956342,  0.41030496, -0.4249819 ,  0.21377441,
        0.14522493, -0.38459416, -0.49647235, -0.80289232, -0.67721666,
       -0.17639015,  0.77487838, -0.63868587,  0.73992083, -0.91109842,
        0.61938545, -0.74261679, -0.99064451,  0.71752097,  0.80088922,
       -0.63775351,  0.06068958,  0.7310408 ,  0.15493111,  0.57096998,
       -0.71385301,  0.13723371, -0.92312376,  0.34737927, -0.2588113 ,
        0.36399535,  0.65223915, -0.51403445, -0.23639762,  0.24629669,
        0.09075624, -0.23237973, -0.04532195,  0.5920402 , -0.30323399,
       -0.05107063,  0.31517798,  0.33266485, -0.26776166,  0.24182959,
       -0.14847547, -0.2392601 ,  0.41767629,  0.61583553, -0.03076779,
       -0.58257334, -0.05000097,  0.24612704,  0.89709697, -0.82386653,
        0.85619805, -0.39007128, -0.55543175,  0.79171329, -0.87119257,
       -0.1880079 , -0.51839686,  0.53278424, -0.94675383,  0.99240395,
        0.39986782, -0.45504811,  0.80710016,  0.95394049,  0.95

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [212]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.34102648  0.50625617  8.97252762 12.43486111  0.21060323  3.88288511
  9.62870246  1.57693529  3.10887268 12.11177104]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [214]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.63800528  7.79503958  0.9579816   3.95681465  5.91408345  7.30665428
  11.68364246  6.66319424  0.19697922  0.59141798]
 [ 1.05855324  8.32127896  8.75541201 11.49669772  1.13459487  8.58089403
   4.39736609  9.43279595 13.47597596  7.12689977]
 [ 2.1665441   6.58966186  8.84036395 10.1466373   2.64393643  6.7108696
   2.75353942  7.77107758 12.57262518  7.38712432]
 [ 0.25153646  6.5311727   0.05775318  3.29219918  3.7832035   5.77330682
  10.57066874  5.52033308  0.12238017  0.59325925]
 [10.68844285  0.99774813 12.44835569  5.31935278 12.74937009  2.05454037
   4.15465268  0.72739418 10.59827732 11.90225976]
 [ 7.79145928  3.7994228   8.4476795   1.74326955 10.725632    4.34922199
   7.19097528  2.26485854  6.59959916  8.00720685]
 [ 4.23871396  8.68638807  4.26937078 10.27861845  4.00556381  9.76440546
   4.33723604  9.45527912 10.92701978  2.41175121]
 [ 1.68245254  0.28282604  5.1617286   3.88822022  3.83738994  0.60435188
   3.59657621  1.42616705  6.83738764  4.17535544]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [218]:
import numpy as np

Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P - Rs // 2)
Z_stop = (P + Rs // 2) + Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]

# Convert lists of slices to tuple of slices
R[tuple(r)] = Z[tuple(z)]

print("Z:")
print(Z)
print("R:")
print(R)


Z:
[[6 3 1 0 8 5 4 9 1 4]
 [7 1 8 3 8 4 1 4 1 4]
 [1 4 3 7 9 7 5 5 0 9]
 [1 1 9 9 5 1 1 5 0 5]
 [5 4 0 4 7 7 0 9 3 6]
 [5 9 4 4 5 5 1 5 4 1]
 [3 2 4 8 2 2 7 4 1 0]
 [3 8 6 4 5 2 1 0 4 2]
 [0 3 0 6 8 2 6 7 3 2]
 [0 6 6 6 9 9 9 9 9 5]]
R:
[[0 0 0 0 0]
 [0 6 3 1 0]
 [0 7 1 8 3]
 [0 1 4 3 7]
 [0 1 1 9 9]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [220]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [228]:
import numpy as np

def sliding_window_view(arr, window_shape):
    # Ensure arr is a NumPy array
    arr = np.asarray(arr)
    
    shape = (arr.size - window_shape + 1, window_shape)
    
    strides = (arr.itemsize,) * 2  # Using itemsize to determine strides
    
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 83. How to find the most frequent value in an array?

In [230]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [232]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 0 1]
   [3 1 2]
   [4 0 1]]

  [[0 1 4]
   [1 2 0]
   [0 1 1]]

  [[1 4 2]
   [2 0 2]
   [1 1 0]]

  [[4 2 1]
   [0 2 0]
   [1 0 3]]

  [[2 1 2]
   [2 0 3]
   [0 3 0]]

  [[1 2 0]
   [0 3 3]
   [3 0 2]]

  [[2 0 1]
   [3 3 1]
   [0 2 2]]

  [[0 1 3]
   [3 1 3]
   [2 2 0]]]


 [[[3 1 2]
   [4 0 1]
   [4 0 2]]

  [[1 2 0]
   [0 1 1]
   [0 2 0]]

  [[2 0 2]
   [1 1 0]
   [2 0 3]]

  [[0 2 0]
   [1 0 3]
   [0 3 3]]

  [[2 0 3]
   [0 3 0]
   [3 3 4]]

  [[0 3 3]
   [3 0 2]
   [3 4 0]]

  [[3 3 1]
   [0 2 2]
   [4 0 0]]

  [[3 1 3]
   [2 2 0]
   [0 0 0]]]


 [[[4 0 1]
   [4 0 2]
   [2 1 1]]

  [[0 1 1]
   [0 2 0]
   [1 1 2]]

  [[1 1 0]
   [2 0 3]
   [1 2 1]]

  [[1 0 3]
   [0 3 3]
   [2 1 4]]

  [[0 3 0]
   [3 3 4]
   [1 4 4]]

  [[3 0 2]
   [3 4 0]
   [4 4 0]]

  [[0 2 2]
   [4 0 0]
   [4 0 3]]

  [[2 2 0]
   [0 0 0]
   [0 3 0]]]


 [[[4 0 2]
   [2 1 1]
   [1 1 4]]

  [[0 2 0]
   [1 1 2]
   [1 4 3]]

  [[2 0 3]
   [1 2 1]
   [4 3 1]]

  [[0 3 3]
   [2 1 4]
   [3 1 3]]

  [[3 3 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [234]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  3 11  5 12]
 [ 3  4  9 11 11]
 [11  9  9 42 14]
 [ 5 11 42  3  7]
 [12 11 14  7  6]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [236]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [237]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays?

In [240]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0
  1 1 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0
  0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1

#### 89. How to get the n largest values of an array

In [248]:
import numpy as np

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

indices = np.argsort(Z)[-n:]

n_largest_values = Z[indices]

print("Array Z:", Z)
print(f"The {n} largest values in Z are:", n_largest_values)



Array Z: [7167 8567 2334 1840 4374 3002 9597 4868 3121 2411 9126 8165  469  356
 5731 4725 2205 8967 2909 7407 9877 1131 1771 9085 8181  616 7145 2424
  713 6421 5093 4091 4146 5569 8084 2964 9497 2306 2661 7613 2061 9588
 5938 8503 8897 3563 7013 8685 9614 6499 3098 7791 5900 5473 2562 2277
 7858 7854 6948 3717 6424 7056 8120 9817 2819 3060 3008 4318 2004  950
 1498 4492 6321 2251 8963 4719  382 2659 5578   66 2193 2752 7934  391
 3281 7237 9849  549 4281  141 3130 5018 6533 4604 2072 1577 3546 2951
  569 5877 4195 5845 9733  147 1036 4724 5495 9269 6334 9233 7216  442
 1998 7274 8688 6069 3530 4876 3631 1642 8790 3374 8488   20 9142 8160
  829 7569  766 5510 6571 5741 8985 7505 9204 1527  881 4952 6262 8838
 4008 7133  757 6513  392 2899 2527 1618 8539 9783 4920 8695 2241 4462
 9728 8175  464 5128 1609  949 5000 9229 7625 1932 9540 7317 3337 3182
 2907 8398 7627 2099 2140 2979 5032 1194 9168  916 9510 9244 5470 7730
 1307 8518  601 7032 1055 2538 3527 7038 8224  517 7650 5277 5375 44

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [242]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array?

In [249]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [250]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.89 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
866 ms ± 112 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
579 ms ± 51.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [251]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [252]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 4]
 [0 0 1]
 [3 1 0]
 [1 1 2]
 [3 4 1]
 [0 4 0]
 [2 0 0]
 [4 4 3]
 [0 3 2]
 [4 2 3]]
[[2 0 4]
 [0 0 1]
 [3 1 0]
 [1 1 2]
 [3 4 1]
 [0 4 0]
 [2 0 0]
 [4 4 3]
 [0 3 2]
 [4 2 3]]
[[2 0 4]
 [0 0 1]
 [3 1 0]
 [1 1 2]
 [3 4 1]
 [0 4 0]
 [2 0 0]
 [4 4 3]
 [0 3 2]
 [4 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation

In [253]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows?

In [254]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [255]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.45155423, 0.51278446, 0.50415874, 0.27791839, 0.16902387,
        0.14080775, 0.45791733, 0.14356368, 0.48454996, 0.25136881],
       [0.1256819 , 0.14272422, 0.14032341, 0.07735353, 0.04704472,
        0.03919127, 0.12745296, 0.03995834, 0.13486566, 0.06996393],
       [0.03700799, 0.04202623, 0.04131929, 0.02277733, 0.01385267,
        0.01154017, 0.03752949, 0.01176603, 0.03971222, 0.02060141],
       [0.4058205 , 0.46084929, 0.45309718, 0.24977062, 0.15190501,
        0.12654664, 0.41153914, 0.12902344, 0.43547439, 0.22591   ],
       [0.58521152, 0.66456553, 0.65338664, 0.36018053, 0.2190539 ,
        0.18248598, 0.59345806, 0.18605765, 0.62797378, 0.32577244],
       [0.57541091, 0.65343597, 0.64244429, 0.35414855, 0.21538538,
        0.17942987, 0.58351935, 0.18294172, 0.61745702, 0.32031669],
       [0.06822574, 0.07747707, 0.0761738 , 0.04199094, 0.02553797,
        0.02127477, 0.06918714, 0.02169117, 0.07321109, 0.03797954],
       [0.59282057, 0.67320635, 0.6618821

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

In [22]:
import numpy as np

# Define parameters
phi = np.arange(0, 10*np.pi, 0.1)
a = 1

# Calculate path coordinates
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

# Compute segment lengths
dr = np.sqrt(np.diff(x)**2 + np.diff(y)**2)  # segment lengths

# Integrate path lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)  # integrate path

# Define equidistant points along the path
num_samples = 200
r_int = np.linspace(0, r.max(), num_samples)  # regular spaced path
x_int = np.interp(r_int, r, x)  # interpolate x coordinates
y_int = np.interp(r_int, r, y)  # interpolate y coordinates

# Print or use x_int, y_int as needed
print("Equidistantly sampled X coordinates:", x_int)
print("Equidistantly sampled Y coordinates:", y_int)


Equidistantly sampled X coordinates: [ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.3

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [13]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [11]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23496607  0.16733919]
